# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPageSlidePicture',
            fields=[
                ('picture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Picture')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_pictures', to='main.MerchantPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('main.picture', models.Model),
        ),
        migrations.RemoveField(
            model_name='merchantpagepicture',
            name='page',
        ),
        migrations.RemoveField(
            model_name='merchantpagepicture',
            name='picture_ptr',
        ),
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Descripci\xc3\xb3n'),
        ),
        migrations.AddField(
            model_name='picture',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'T\xc3\xadtulo'),
        ),
        migrations.DeleteModel(
            name='MerchantPagePicture',
        ),
    ]
