# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161221_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageRelatedSocialMediaLink',
            new_name='MerchantPageRelatedSocialMediaLink',
        ),
    ]
