# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161130_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Referencia', 'verbose_name_plural': 'Referencias'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(help_text=b'Describe tu producto al p\xc3\xbablico', verbose_name=b'Descripcion'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'Precio'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stock_quantity',
            field=models.IntegerField(verbose_name=b'Cantidad de stock'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='value',
            field=models.CharField(blank=True, help_text=b"Ejemplo: Si tu caracter\xc3\xadstica es 'Color', valor podr\xc3\xada ser 'Verde' ", max_length=200, null=True, verbose_name=b'Valor de caracter\xc3\xadstica'),
        ),
    ]
