# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20161201_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='feature',
            field=models.ForeignKey(blank=True, help_text=b'Caracter\xc3\xadsticas para esta referencia. Ejemplo: Color', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Feature'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='value',
            field=models.CharField(blank=True, help_text=b"Ejemplo: Si tu caracter\xc3\xadstica es 'Color', valor podr\xc3\xada ser 'Verde'", max_length=200, null=True, verbose_name=b'Valor de caracter\xc3\xadstica'),
        ),
    ]
