# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_principal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='principal',
            new_name='main_image',
        ),
    ]
