# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_auto_20161203_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.CharField(max_length=25)),
                ('buyer_name', models.CharField(max_length=150)),
                ('buyer_phone', models.CharField(max_length=12)),
                ('buyer_address', models.CharField(max_length=255)),
                ('buyer_email', models.CharField(max_length=255)),
                ('buyer_city', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[(b'IP', b'En progreso'), (b'PE', b'Pendiente'), (b'CO', b'Confirmada'), (b'DL', b'Enviada'), (b'CA', b'Cancelada')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Variant')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_code', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
