# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20161215_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Comprador'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Direcci\xc3\xb3n de env\xc3\xado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.City', verbose_name=b'Ciudad de env\xc3\xado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'IP', b'En progreso'), (b'PE', b'Pendiente'), (b'CO', b'Confirmada'), (b'DL', b'Enviada'), (b'CA', b'Cancelada')], default=b'IP', max_length=2, verbose_name=b'Estado'),
        ),
    ]
