# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20161226_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Compra'},
        ),
    ]
